title: Shiraz Khan
css: /assets/css/style.scss
#logo: /assets/img/head_circle.png
description: >
  Email: 2193shikhan@gmail.com <br>
  <a href="https://www.linkedin.com/in/shiraz-khan1/">LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
