title: Shiraz Khan
css: /assets/css/style.scss
#logo: /assets/img/head_circle.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
nav:
  - name: Home
    link: /
  - name: Projects
    link: /projects

# Markdown settings
markdown: kramdown
highlighter: rouge
