title: Shiraz Khan
css: /assets/css/style.scss
#logo: /assets/img/head_circle.png
description: 2193shikhan@gmail.com https://www.linkedin.com/in/shiraz-khan1/ 
show_downloads: false
theme: jekyll-theme-minimal
